name: Build macOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-10.15

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        brew install openslide libomp

    - name: Download FAST
      uses: robinraju/release-downloader@main
      with:
        repository: "AICAN-Research/FAST-Pathology-dependencies"
        latest: true
        fileName: "fast_mac10.13.tar.xz"
        out-file-path: "downloads"

    - name: Extract FAST
      run: |
        cd ${{github.workspace}}/downloads/
        tar -xf fast_macos10.13.tar.xz -C ${{github.workspace}}/downloads/
        mv ${{github.workspace}}/downloads/fast_*/fast ${{github.workspace}}/

    - name: Configure CMake
      run: |
        cmake -B ${{github.workspace}}/build -DFAST_DIR=${{github.workspace}}/fast/cmake/

    - name: Build FastPathology
      run: cmake --build ${{github.workspace}}/build --config Release --target fastpathology -j 4

    - name: Build Package
      run: cmake --build ${{github.workspace}}/build --config Release --target package -j 4

    - name: Upload Bundle package
      uses: actions/upload-artifact@v2
      with:
        name: Archive package (tar.xz)
        path: ${{github.workspace}}/build/fastpathology_*.tar.xz
        if-no-files-found: error
