name: Build Ubuntu

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types: [ published ]
    

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Download FAST
      uses: robinraju/release-downloader@main
      with:
        repository: "AICAN-Research/FAST-Pathology-dependencies"
        latest: true
        fileName: "fast_ubuntu18.04.tar.xz"
        out-file-path: "downloads"

    - name: Extract FAST
      run: |
        cd ${{github.workspace}}/downloads/
        tar -xf fast_*.tar.xz -C ${{github.workspace}}/downloads/
        mv ${{github.workspace}}/downloads/fast_*/fast ${{github.workspace}}/

    - name: Install dependencies
      run: |
        sudo snap install cmake --classic # Use snap to get more recent version of cmake on Ubuntu 18.04
        sudo apt install g++ patchelf
        sudo apt install '^libxcb.*-dev' libx11-xcb-dev libglu1-mesa-dev libxrender-dev libxi-dev libxkbcommon-dev libxkbcommon-x11-dev
        sudo apt install libopenslide-dev  # Needed for WSI module

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DFAST_DIR=${{github.workspace}}/fast/cmake/

    - name: Build FastPathology
      run: cmake --build ${{github.workspace}}/build --config Release -j 4

    - name: Build Package
      run: cmake --build ${{github.workspace}}/build --config Release --target package -j 4

    - name: Upload Debian package
      uses: actions/upload-artifact@v2
      with:
        name: Debian package
        path: ${{github.workspace}}/build/fastpathology_*.deb
        if-no-files-found: error
        
    - name: Upload Debian package to release
      if: ${{ github.event_name == 'release' }}
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{github.workspace}}/build/fastpathology_*.deb
        file_glob: true
        tag: ${{ github.ref }}
        overwrite: true
