name: Build macOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types: [ published ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-11

    steps:
    - name: Checkout
      uses: actions/checkout@v3.3.0

    - name: Install dependencies
      run: |
        brew install openslide libomp

    - name: Download FAST
      uses: robinraju/release-downloader@main
      with:
        repository: "AICAN-Research/FAST-Pathology-dependencies"
        latest: true
        fileName: "fast_macos10.13.tar.xz"
        out-file-path: "downloads"

    - name: Extract FAST
      run: |
        cd ${{github.workspace}}/downloads/
        tar -xf fast_*.tar.xz -C ${{github.workspace}}/downloads/
        mv ${{github.workspace}}/downloads/fast_*/fast ${{github.workspace}}/

    - name: Configure CMake
      run: |
        cmake -B ${{github.workspace}}/build -DFAST_DIR=${{github.workspace}}/fast/cmake/

    - name: Build FastPathology
      run: cmake --build ${{github.workspace}}/build --config Release --target fastpathology -j 4

    - name: Build Package
      run: cmake --build ${{github.workspace}}/build --config Release --target package -j 4

    - name: Upload Bundle package
      uses: actions/upload-artifact@v2
      with:
        name: macOS package
        path: ${{github.workspace}}/build/fastpathology_*.dmg
        if-no-files-found: error
        
    - name: Upload archive package to release
      if: ${{ github.event_name == 'release' }}
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{github.workspace}}/build/fastpathology_*.dmg
        file_glob: true
        tag: ${{ github.ref }}
        overwrite: true
