name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Create a subdirectory
      run: |
        mkdir subdir

    - name: Download FAST
      uses: dsaltares/fetch-gh-release-asset@master
      id: get_release
      uses: ./
      with:
        repo: "smistad/FAST"
        version: "tags/v4.1.0"
        file: "fast_ubuntu18.04_4.1.0.deb"
        target: "subdir/fast_ubuntu18.04_4.1.0.deb"
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Display the details
      run: |
        echo ${{ steps.get_release.outputs.version }}
        echo ${{ steps.get_release.outputs.name }}
        echo ${{ steps.get_release.outputs.body }}
        ls -l subdir/fast_ubuntu18.04_4.1.0.deb

    # - uses: actions/checkout@v2
    # - name: Install dependencies
    #   run: |
    #     ls

    # - name: Configure CMake
    #   run: |
    #     cmake ${{github.workspace}} -B ${{github.workspace}}/build `

    # - name: Build
    #   run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -j 4

    # - name: Package
    #   run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target package -j 4
    
    # - name: Upload Windows installer
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: Window installer
    #     path: ${{github.workspace}}/build/FastPathology_*.exe
    #     if-no-files-found: error

    # - name: Upload archive package
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: Archive package (zip)
    #     path: ${{github.workspace}}/build/FastPathology_*.zip
    #     if-no-files-found: error