name: Build Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-2019

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Download FAST (artifact)
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        workflow: CI-windows.yml
        workflow_conclusion: success
        branch: master
        event: push
        name: "Archive package (zip)"
        repo: smistad/FAST

    - name: Uncompress zip
      run: |
        tar -xzf "./Archive package (zip).zip"
        tar -xzf ./fast_windows_4.2.1.zip
      
    - name: Configure CMake
      run: |
        cmake -B ${{github.workspace}}/build `
            -DFAST_DIR=${{github.workspace}}/fast_windows_4.2.1/fast/cmake `
            -G "Visual Studio 16 2019" `
            -A x64

    - name: Build FastPathology
      run: cmake --build ${{github.workspace}}/build --config Release --target fastpathology -j 4

    - name: Build Package
      run: cmake --build ${{github.workspace}}/build --config Release --target package -j 4

    - name: Upload Windows installer
      uses: actions/upload-artifact@v2
      with:
        name: Windows package
        path: ${{github.workspace}}/build/fastpathology_*.exe
        if-no-files-found: error
