name: Build Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types: [ published ]  
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Download FAST
      uses: robinraju/release-downloader@main
      with:
        repository: "AICAN-Research/FAST-Pathology-dependencies"
        latest: true
        fileName: "fast_windows.zip"
        out-file-path: "downloads"

    - name: Extract FAST
      run: |
        cd ${{github.workspace}}/downloads/
        tar -xzf fast_windows.zip -C ${{github.workspace}}/downloads/
        mv ${{github.workspace}}/downloads/fast_*/fast ${{github.workspace}}/

    - name: Configure CMake
      run: |
        cmake -B ${{github.workspace}}/build `
            -DFAST_DIR=${{github.workspace}}/fast/cmake/ `
            -G "Visual Studio 16 2019" `
            -A x64

    - name: Build FastPathology
      run: cmake --build ${{github.workspace}}/build --config Release --target fastpathology -j 4

    - name: Build Package
      run: cmake --build ${{github.workspace}}/build --config Release --target package -j 4

    - name: Upload Windows installer
      uses: actions/upload-artifact@v2
      with:
        name: Windows package
        path: ${{github.workspace}}/build/fastpathology_*.exe
        if-no-files-found: error
        
    - name: Upload Windows installer to release
      if: ${{ github.event_name == 'release' }}
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{github.workspace}}/build/fastpathology_*.exe
        file_glob: true
        tag: ${{ github.ref }}
        overwrite: true
