name: Build Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Download FAST
      run: |
        curl.exe -OL https://github.com/smistad/FAST/releases/download/v4.1.0/fast_windows_4.1.0.exe
        ls
    # curl.exe -OL https://github.com/smistad/FAST/suites/3988368847/artifacts/100451804/zip

    - name: Test Windows 64 bit
      run: |
        [Environment]::Is64BitOperatingSystem

    - name: Test Windows 32 bit
      run: |
        [Environment]::Is32BitOperatingSystem

    - name: Install dependencies
      run: |
        pip3 install numpy==1.19.5

    - name: Install FAST
      run: |
        ./fast_windows_4.1.0.exe
      #Start-Process -Wait -FilePath "./fast_windows_4.1.0.exe" -ArgumentList "/S" -PassThru
      #./fast_windows_4.1.0.exe /S
      
    - name: Configure CMake
      run: |
        cmake -B ${{github.workspace}}/build

    - name: Build FastPathology
      run: |
        cmake --build ${{github.workspace}}/build --config $${{env.BUILD_TYPE}} -j 4

    - name: Build Package
      run: |
        cmake --build ${{github.workspace}}/build --config $${{env.BUILD_TYPE}} --target package -j 4

    - name: Upload Windows installer
      uses: actions/upload-artifact@v2
      with:
        name: Windows package
        path: ${{github.workspace}}/build/fastpathology_*.exe
        if-no-files-found: error

    # - name: Upload archive package
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: Archive package (tar.xz)
    #     path: ${{github.workspace}}/build/fastpathology_*.tar.xz
    #     if-no-files-found: error
