name: Build macOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install dependencies
      run: pip3 install numpy==1.19.5

    - name: Download FAST
      run: |
        curl -OL https://github.com/smistad/FAST/releases/download/v4.1.0/fast_macosx10.13_4.1.0.tar.xz
        ls
        gunzip fast_macosx10.13_4.1.0.tar.xz
        ls
        tar -xzf ./fast_macosx10.13_4.1.0.tar
        ls

    - name: Debugging
      run: |
        ls
        echo
        cd fast_macosx10.13_4.1.0
        ls
        echo
        cd fast
        ls
      
    - name: Configure CMake
      run: |
        cmake -B ${{github.workspace}}/build `
            -DFAST_DIR=${{github.workspace}}/fast_macosx10.13_4.1.0/fast/cmake `

    - name: Build FastPathology
      run: cmake --build ${{github.workspace}}/build --config Release --target fastpathology -j 4

    - name: Build Package
      run: cmake --build ${{github.workspace}}/build --config Release --target package -j 4

    - name: Upload Windows installer
      uses: actions/upload-artifact@v2
      with:
        name: Windows package
        path: ${{github.workspace}}/build/fastpathology_*.exe
        if-no-files-found: error
