name: Build macOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-10.15

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        brew install openslide libomp

    - name: Download FAST
      run: |
        curl -OL https://github.com/smistad/FAST/releases/download/v4.1.0/fast_macosx10.13_4.1.0.tar.xz
        gunzip fast_macosx10.13_4.1.0.tar.xz
        tar -xzf ./fast_macosx10.13_4.1.0.tar
      
    - name: Configure CMake
      run: |
        cmake -B ${{github.workspace}}/build \
            -DFAST_DIR=${{github.workspace}}/fast_macosx10.13_4.1.0/fast/cmake/

    - name: Build FastPathology
      run: cmake --build ${{github.workspace}}/build --config Release --target fastpathology -j 4

    - name: Build Package
      run: cmake --build ${{github.workspace}}/build --config Release --target package -j 4

    - name: Upload Bundle package
      uses: actions/upload-artifact@v2
      with:
        name: Bundle package (macOS)
        path: ${{github.workspace}}/build/fastpathology_*.pkg
        if-no-files-found: error
