name: Build Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Download FAST
      run: |
        curl.exe -OL "https://github.com/smistad/FAST/suites/3988368847/artifacts/100451804/Archive package (zip).zip"
        ls 
        tar xzf "Archive package (zip)"
        ls
        tar xzf "fast_windows_4.1.0.zip"
        ls

    #curl -OL https://raw.githubusercontent.com/smistad/FAST/master/releases/download/v4.1.0/fast_windows_4.1.0.exe
    #ls
    - name: Test Windows 64 bit
      run: |
        [Environment]::Is64BitOperatingSystem

    - name: Test Windows 32 bit
      run: |
        [Environment]::Is32BitOperatingSystem

    - name: Install dependencies
      run: |
        pip3 install numpy==1.19.5
      
    - name: Configure CMake
      run: |
        cmake -B ${{github.workspace}}/build `
            -DFAST_DIR=${{github.workspace}}/fast_windows_4.1.0/fast/cmake

    - name: Build FastPathology
      run: |
        cmake --build ${{github.workspace}}/build --config $${{env.BUILD_TYPE}} -j 4

    - name: Build Package
      run: |
        cmake --build ${{github.workspace}}/build --config $${{env.BUILD_TYPE}} --target package -j 4

    - name: Upload Windows installer
      uses: actions/upload-artifact@v2
      with:
        name: Windows package
        path: ${{github.workspace}}/build/fastpathology_*.exe
        if-no-files-found: error

    # - name: Upload archive package
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: Archive package (tar.xz)
    #     path: ${{github.workspace}}/build/fastpathology_*.tar.xz
    #     if-no-files-found: error
