name: Build macOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release
  MACOSX_DEPLOYMENT_TARGET: 10.13

jobs:
  build:
    runs-on: macos-10.15

    steps:
    - uses: actions/checkout@v2
    - name: Setup pyenv
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        MACOSX_DEPLOYMENT_TARGET: ${{env.MACOSX_DEPLOYMENT_TARGET}}
        PYTHON_CONFIGURE_OPTS: "--enable-framework"
      uses: "gabrielfalcao/pyenv-action@v5"
      with:
          default: 3.6.9

    - name: Install dependencies
      run: |
        brew install openslide libomp

    - name: Download FAST (artifact)
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{secrets.FP}}
        workflow: CI-mac.yml
        workflow_conclusion: success
        branch: master
        event: push
        name: "Archive package (tar.xz)"
        repo: smistad/FAST

    - name: Install FAST
      run: |
        gunzip fast_macosx10.13_4.1.0.tar.xz
        tar -xzf ./fast_macosx10.13_4.1.0.tar
      
    - name: Configure CMake
      run: |
        cmake -B ${{github.workspace}}/build \
            -DFAST_DIR=${{github.workspace}}/fast_macosx10.13_4.1.0/fast/cmake/

    - name: Build FastPathology
      run: cmake --build ${{github.workspace}}/build --config Release --target fastpathology -j 4

    - name: Build Package
      run: cmake --build ${{github.workspace}}/build --config Release --target package -j 4

    - name: Upload Bundle package
      uses: actions/upload-artifact@v2
      with:
        name: Archive package (tar.xz)
        path: ${{github.workspace}}/build/fastpathology_*.tar.xz
        if-no-files-found: error
